### ISSUE TITLE
Scroll to a grid item programmatically

### ISSUE THREAD

**Issue by xMonty** [AlexBacich/sticky-headers-table#9]
Hi, 
Any way to scroll to a particular location in grid programmatically?
thanks

**Comment by mithunadhikari40** [comment]
I don't think there is no such method or property given. But I managed to get around by adding some method on the library itself.
I added a method inside `_SyncScrollController` class in `table_sticky_header.dart`
`  void justJump(double offset, ScrollController scrollController) {
    scrollController.jumpTo(offset);
  }`

Since I just need to scroll horizontally, I added this snippet of code inside `initState` method of `_StickyHeadersTableState` class like: 
`if (widget.offset != null) {
      SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
        Future.delayed(Duration(seconds: 2), () {
          _horizontalSyncController.justJump(
              widget.offset, _horizontalBodyController);
//          _verticalSyncController.justJump(
//              widget.offset, _verticalTitleController);
        });
      });
    }`
I put 2 seconds delay because I was getting an error but `SchedulerBinding` should have worked fine. 
And then I added offset property in `StickyHeadersTable` class like 
`final double offset;`
and then initialize this property in the constructor.
And to use it, I am passing offset value as the index on which I want to jump to multiplied by 70. For e.g if I want to jump to 17th index element, I would pass offset value as 70*17. But you can play around that value to suit your need.

**Comment by albrnick** [comment]
Another approach would be to use https://pub.dev/packages/scroll_to_index . You'd have to wrap your cell contents with 2 AutoTags. One for the row index, ,and one for the column index.  And you'd have to modify this library to somehow work in the scroll_to_index controllers.

**Comment by AlexBacich** [comment]
I have added ability to jump to index for X and Y. It will be available since 2.0.3 (will be published in a day or two). 
Use these parameters: 
```
scrollOffsetIndexX
scrollOffsetIndexY
```
